# Generated by Django 3.2.4 on 2021-08-23 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_type', models.CharField(choices=[('L', 'Person to learn about'), ('C', 'Person to reach out to'), ('G', 'Person I am grateful for')], default='L', max_length=1)),
                ('name', models.CharField(max_length=50)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.challenge')),
            ],
        ),
    ]
