# Generated by Django 3.2.4 on 2021-08-23 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_people'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='selected_type',
            new_name='type',
        ),
    ]
