# Generated by Django 3.2.4 on 2021-08-24 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_rename_places_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='place',
            new_name='name',
        ),
    ]
